### PR TITLE
Implement faked-list detection

### PR DESCRIPTION
**Pull request by kylegibson**
https://github.com/kylegibson/pydocx/compare/issue_151...kylegibson:issue_134

Scenarios:

## Full-sequence nested partial-faked list using indentation, local style

1, 2, 2.1, 2.2 are "real" lists. 3, 3.1, 3.2 are faked using indentation

```
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Normal"/>
        <w:numPr>
          <w:ilvl w:val="0"/>
          <w:numId w:val="1"/>
        </w:numPr>
        <w:rPr/>
      </w:pPr>
      <w:r>
        <w:rPr/>
        <w:t>a</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Normal"/>
        <w:numPr>
          <w:ilvl w:val="0"/>
          <w:numId w:val="1"/>
        </w:numPr>
        <w:rPr/>
      </w:pPr>
      <w:r>
        <w:rPr/>
        <w:t>b</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Normal"/>
        <w:numPr>
          <w:ilvl w:val="1"/>
          <w:numId w:val="1"/>
        </w:numPr>
        <w:rPr/>
      </w:pPr>
      <w:r>
        <w:rPr/>
        <w:t>c</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Normal"/>
        <w:numPr>
          <w:ilvl w:val="1"/>
          <w:numId w:val="1"/>
        </w:numPr>
        <w:rPr/>
      </w:pPr>
      <w:r>
        <w:rPr/>
        <w:t>d</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Normal"/>
        <w:tabs>
          <w:tab w:val="left" w:pos="542" w:leader="none"/>
        </w:tabs>
        <w:ind w:left="0" w:right="0" w:firstLine="360"/>
        <w:rPr/>
      </w:pPr>
      <w:r>
        <w:rPr/>
        <w:t>3.   e</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Normal"/>
        <w:tabs>
          <w:tab w:val="left" w:pos="542" w:leader="none"/>
        </w:tabs>
        <w:ind w:left="0" w:right="0" w:firstLine="720"/>
        <w:rPr/>
      </w:pPr>
      <w:r>
        <w:rPr/>
        <w:t>1.   f</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Normal"/>
        <w:tabs>
          <w:tab w:val="left" w:pos="542" w:leader="none"/>
        </w:tabs>
        <w:ind w:left="0" w:right="0" w:firstLine="720"/>
        <w:rPr/>
      </w:pPr>
      <w:r>
        <w:rPr/>
        <w:t>2.   g</w:t>
      </w:r>
    </w:p>
```

## Full-sequence nested faked list using TABS, local style

```
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Normal"/>
        <w:tabs>
          <w:tab w:val="left" w:pos="542" w:leader="none"/>
        </w:tabs>
        <w:ind w:left="0" w:right="0" w:hanging="0"/>
        <w:rPr/>
      </w:pPr>
      <w:r>
        <w:rPr/>
        <w:tab/>
        <w:t>1.   a</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Normal"/>
        <w:tabs>
          <w:tab w:val="left" w:pos="542" w:leader="none"/>
        </w:tabs>
        <w:ind w:left="0" w:right="0" w:hanging="0"/>
        <w:rPr/>
      </w:pPr>
      <w:r>
        <w:rPr/>
        <w:tab/>
        <w:tab/>
        <w:t>1. aa</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Normal"/>
        <w:tabs>
          <w:tab w:val="left" w:pos="542" w:leader="none"/>
        </w:tabs>
        <w:ind w:left="0" w:right="0" w:hanging="0"/>
        <w:rPr/>
      </w:pPr>
      <w:r>
        <w:rPr/>
        <w:tab/>
        <w:tab/>
        <w:t>2. ab</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Normal"/>
        <w:tabs>
          <w:tab w:val="left" w:pos="542" w:leader="none"/>
        </w:tabs>
        <w:ind w:left="0" w:right="0" w:hanging="0"/>
        <w:rPr/>
      </w:pPr>
      <w:r>
        <w:rPr/>
        <w:tab/>
        <w:t>2.   b</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Normal"/>
        <w:tabs>
          <w:tab w:val="left" w:pos="542" w:leader="none"/>
        </w:tabs>
        <w:ind w:left="0" w:right="0" w:hanging="0"/>
        <w:rPr/>
      </w:pPr>
      <w:r>
        <w:rPr/>
        <w:tab/>
        <w:t>3.   c</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Normal"/>
        <w:tabs>
          <w:tab w:val="left" w:pos="542" w:leader="none"/>
        </w:tabs>
        <w:ind w:left="0" w:right="0" w:hanging="0"/>
        <w:rPr/>
      </w:pPr>
      <w:r>
        <w:rPr/>
        <w:tab/>
        <w:tab/>
        <w:t>1. ca</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Normal"/>
        <w:tabs>
          <w:tab w:val="left" w:pos="542" w:leader="none"/>
        </w:tabs>
        <w:ind w:left="0" w:right="0" w:hanging="0"/>
        <w:rPr/>
      </w:pPr>
      <w:r>
        <w:rPr/>
        <w:tab/>
        <w:tab/>
        <w:t>2. cb</w:t>
      </w:r>
    </w:p>
```

## Sequences to handle

* A, B, C, ... Z
* a, b, c, ... Z
* 1, 2, 3, ...
* I, II, III, ...
* (1), (2), (3), ...
* 1), 2), 3), ...

### CODE REVIEW

**Comment by kylegibson** [comment]
TODO

- [ ] Add test case for only indentation (no tabs)
- [ ] Add test case for level decreasing
- [ ] Implement level decreasing
- [ ] Add test case for a real list contained within a faked list
- [ ] Move implementation to an optional NumberingSpanBuilder extension
- [ ] Write test cases for the various helpers used (initial tabs, etc)

**Comment by kylegibson** [comment]
The "{digit} " pattern doesn't work very well, for example: "A dog walked" would be converted to an upper alpha list consisting of "dog walked". Likewise, "I am ready" would likewise be converted to an upper roman list consisting of "am ready".

**Comment by winhamwr** [comment]
> The "{digit} " pattern doesn't work very well, for example: "A dog walked" would be converted to an upper alpha list consisting of "dog walked". Likewise, "I am ready" would likewise be converted to an upper roman list consisting of "am ready".

Does the semantinator implement it like that? I was expecting it to only catch something like `A. ` or `A) ` and then, ideally only if there was a `B. ` after it.

**Comment by kylegibson** [comment]
> Does the semantinator implement it like that? I was expecting it to only catch something like A. or A) and then, ideally only if there was a B. after it.

No, fortunately the semantinator does not. I did it because I initially thought it would be useful. QA has proven that hypothesis to be very, very wrong.

**Comment by jlward** [comment]
> No, fortunately the semantinator does not. I did it because I initially thought it would be useful. QA has proven that hypothesis to be very, very wrong. 

The semantinator does some look ahead. It also won't convert to a real list if there are some flaws. It's pretty complicated, you'll have to look at the test cases to get a better idea of what actually works.

**Comment by kylegibson** [comment]
I just realized my response above could be misinterpreted, so I updated it.

**Comment by kylegibson** [comment]
Need the recent several commits reviewed

**Comment by michaelgzoller** [comment]
:+1:

**Pull request merged**
