### PR TITLE
Rotate image when exporting to html

### PR DESCRIPTION
**Pull request by botzill**

### CODE REVIEW

**Comment by jhubert** [comment]
@kylegibson It would be great to get this reviewed and merged. Anything I can do to help?

**Comment by kylegibson** [comment]
Hi Jeremy,

Apologies for not having this reviewed sooner. I'll review it ASAP.

Thanks,

-Kyle

**Comment by jhubert** [comment]
Not a problem and wasn't meant to be a hard push. You guys are awesome and I love what you're building! Really appreciate you taking the time.

**Comment by kylegibson** [comment]
Hi Chirica, the code looks good. Would it be possible to use a smaller image (with a smaller base64 footprint)?

**Comment by jhubert** [comment]
@botzill I've made a much smaller file you can use: 
[image_rotation_issue.docx](https://github.com/CenterForOpenScience/pydocx/files/59877/image_rotation_issue.docx)

**Comment by botzill** [comment]
Done, I replaced with that smaller file.

**Pull request merged**
